### ISSUE TITLE
Can't get this to install / run

### ISSUE THREAD

**Issue by chrislachance** [Wox-launcher/Wox.Plugin.BrowserBookmark#1]
Tried installing using WPM install method, and manually placing source in the appropriate plugin folder. What am I doing wrong? Or is this project not yet complete?

**Comment by PickRelated** [comment]
+1 What do I do to make it work?

**Comment by lances101** [comment]
Hey there, @PickRelated. I have updated the plugin to work with a recent version of Wox. The problem is that @qianlifeng is the one that has access on getwox.com over the plugin, so me and @happlebao cannot update the binary there. 

I will make a fresh build now, upload it as a release and comment in this thread

**Comment by bao-qian** [comment]
@lances101 the plugin has been taken down, could you upload the binary?

**Comment by bao-qian** [comment]
I mean upload it to getwox

**Comment by PickRelated** [comment]
Well, thank you sirs! I did not expect such a quick reaction!

**Comment by lances101** [comment]
@happlebao, thanks! I will upload the binary now then.

**Comment by lances101** [comment]
@happlebao, I've uploaded the plugin. But I'm having issues with installing it. `wpm install` gives me a "not found". 
[Heres the plugin itself](http://www.getwox.com/plugin/85). If you try downloading it via getwox it will also give you a 404. I don't know what is the issue and I don't have access to actually check

**Comment by bao-qian** [comment]
@lances101 the server has been migrated. it seems like there is some file permission issue on  new server, so the file is not actually uploaded. I'm investigating now.

**Comment by lances101** [comment]
@happlebao Okay. Please notify me once you fix that. Thanks.

**Comment by lances101** [comment]
@PickRelated, as a temporal fix, [I uploaded the plugin as a release here](https://github.com/Wox-launcher/Wox.Plugin.BrowserBookmark/releases/download/1.1.1/Wox.Plugin.BrowserBookmark.wox). Drop the `.wox` on Wox's window and it will prompt to install it.

**Comment by bao-qian** [comment]
@lances101 try again

**Comment by lances101** [comment]
@happlebao yep. Everything seems to work.

**Comment by PickRelated** [comment]
Today I installed it with `wpm`. Everything works. Love it. Thanks guys!
